### ISSUE TITLE
Application Creation and Update

### ISSUE THREAD

**Issue by Brojowski** [hacksu/khe-frontend-lib#16]

**Comment by bhollan5** [comment]
Is this fixed? If so, can we update the Wiki to explain how it works? I can also do the wiki if it's easier

**Comment by IAPark** [comment]
I believe so with but I don't know for sure https://github.com/hacksu/khe-frontend-lib/blob/master/src/ApplicationManager.ts

**Comment by Brojowski** [comment]
A wiki page has been added:

https://github.com/hacksu/khe-frontend-lib/wiki/Applications
